# Generated by Django 4.1.2 on 2022-10-18 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cant_temas', models.CharField(max_length=40)),
                ('fec_lanzamiento', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='caratula')),
            ],
        ),
        migrations.CreateModel(
            name='Discografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Interprete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('duracion', models.IntegerField()),
                ('autor', models.CharField(max_length=255)),
                ('compositor', models.CharField(max_length=255)),
                ('cod_album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disqueria.album')),
                ('interprete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disqueria.interprete')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='discografica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disqueria.discografica'),
        ),
        migrations.AddField(
            model_name='album',
            name='formato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disqueria.formato'),
        ),
        migrations.AddField(
            model_name='album',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disqueria.genero'),
        ),
        migrations.AddField(
            model_name='album',
            name='interprete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disqueria.interprete'),
        ),
    ]
